// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evbgtkckhibsvfiueerm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2Ymd0a2NraGlic3ZmaXVlZXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Njk5NjgsImV4cCI6MjA3MzE0NTk2OH0.SEaRJRgs4WsfMKquaEIJNmbt0jyQADXkJ-1RQZqNKC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});